services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: rock-spotter-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: rock-spotter
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - rock-spotter-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rock-spotter-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/rock-spotter
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - UPLOAD_PATH=/app/uploads
      - MAX_FILE_SIZE=5242880
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mongodb
    networks:
      - rock-spotter-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rock-spotter-web
    restart: unless-stopped
    ports:
      - "3002:80"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    networks:
      - rock-spotter-network

volumes:
  mongodb_data:
    driver: local
  uploads_data:
    driver: local

networks:
  rock-spotter-network:
    driver: bridge
